name: production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn global add @vue/cli
        yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Deploy to S3
      run: yarn deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
